### ISSUE TITLE
[Discussion] Database

### ISSUE THREAD

**Issue by piggylux** [Sylux6/WatanaBot#24]
- Backup: we should make regular database backup just in case.
`.\pg_dump.exe -h localhost -p 5432 -U yousoro watanabot > E:\bak.sql`
- Maybe use another ORM than hibernates, simpler and more kotlin oriented
  - ~~[ebean](https://github.com/ebean-orm/ebean)~~
  - [Exposed](https://github.com/JetBrains/Exposed)
  - ~~[Ktorm](https://github.com/vincentlauvlwj/Ktorm)~~

**Comment by Sylux6** [comment]
Should change the database version system with an actual revision migration system

But lazy

**Comment by Sylux6** [comment]
`.\pg_dump.exe -h localhost -p 5432 -U yousoro watanabot > E:\bak.sql`

**Comment by piggylux** [comment]
Use [Exposed](https://github.com/JetBrains/Exposed)

Resources:
- https://github.com/JetBrains/Exposed/wiki/FAQ
- https://github.com/JetBrains/Exposed/issues/167 / https://github.com/JetBrains/Exposed/issues/167#issuecomment-480199613
- https://medium.com/@OhadShai/first-steps-with-kotlin-exposed-cb361a9bf5ac
- https://github.com/KenjiOhtsuka/harmonica
