### ISSUE TITLE
Update imageboard-api

### ISSUE THREAD

**Issue by Kodehawa** [Sylux6/WatanaBot#30]
Just poking here because you're using an old version of imageboard-api (2.0.5) and latest it's 2.1

Also looking at your implementation I saw some stuff that could be improved (see, you can search using tags/rating) 
Some implementation of it can be found [on the project tests](https://github.com/Kodehawa/imageboard-api/blob/master/src/test/java/net/kodehawa/lib/imageboards/ImageBoardTest.java) and in [Mantaro](https://github.com/Mantaro/MantaroBot/blob/master/src/main/java/net/kodehawa/mantarobot/commands/image/ImageboardUtils.java#L57)

**Comment by piggylux** [comment]
Thank you~
I'll think about a better implementation later https://github.com/Sylux6/WatanaBot/issues/32
